from django.conf import settings

from .data import format_price, get_product


UI_TEXT = {
    "en": {
        "home": "Home",
        "products": "Products",
        "price": "Price",
        "rating": "Rating",
        "about": "About",
        "contact": "Contact",
        "cart": "Cart",
        "catalog": "Catalog",
        "checkout": "Checkout",
        "support": "Support",
        "footer_text": "Modern online shop for home appliances, delivery, and easy checkout.",
        "ad": "Ad",
        "catalog_sections": "Catalog sections",
        "all_smartphones": "All smartphones",
        "large_appliances": "Large appliances",
        "refrigerators": "Refrigerators",
        "washing_machines": "Washing machines",
        "dishwashers": "Dishwashers",
        "ovens": "Ovens",
        "kitchen_for": "For the kitchen",
        "microwaves": "Microwaves",
        "air_fryers": "Air fryers",
        "coffee_machines": "Coffee machines",
        "blenders": "Blenders",
        "meat_grinders": "Meat grinders",
        "climate_care": "Climate and care",
        "air_purifiers": "Air purifiers",
        "water_heaters": "Water heaters",
        "irons": "Irons",
        "hair_dryers": "Hair dryers",
        "brands": "Brands",
        "sales_discounts": "Deals and discounts",
        "air_conditioners": "Air conditioners",
        "vacuum_cleaners": "Vacuum cleaners",
        "laptops": "Laptops",
        "login": "Login",
        "login_with_phone": "Continue with phone",
        "login_with_google": "Continue with Google",
        "login_or": "or",
        "favorites": "Favorites",
        "compare": "Compare",
        "compare_products": "Compare products",
        "add_to_compare": "Compare",
        "remove_from_compare": "Compared",
        "comparison_empty": "No products selected for comparison yet.",
        "recently_viewed": "Recently viewed",
        "stock": "Stock",
        "availability": "Availability",
        "search_placeholder": "Search smartphones, appliances, and brands",
        "login_title": "Sign in to TechShop",
        "phone_placeholder": "+998 00 000-00-00",
        "get_code": "Get activation code",
        "code_title": "Enter confirmation code",
        "code_placeholder": "4-digit code",
        "confirm_code": "Confirm",
        "demo_code": "Demo code",
        "change_phone": "Change phone",
        "logout": "Log out",
        "signed_in_as": "Signed in as",
        "profile_title": "My information",
        "full_name": "Full name",
        "profile_type": "Profile type",
        "google_account": "Google account",
        "phone_account": "Phone sign-in",
        "back_to_catalog": "Back to catalog",
        "my_information": "My information",
        "orders": "Orders",
        "sign_in_or_create": "Sign in or create an account",
        "sign_in": "Sign in",
        "agreement": "By continuing, you agree to personal data processing and public offer terms.",
        "new_season": "New season technology",
        "hero_title": "Home appliances for every room.",
        "hero_text": "Find refrigerators, washers, TVs, kitchen appliances, and climate control products in one compact catalog.",
        "shop_catalog": "Shop catalog",
        "featured_deals": "Featured deals",
        "warranty": "2-year warranty",
        "secure_checkout": "Secure checkout",
        "fast_delivery": "Fast delivery",
        "offer_title": "Up to 18% off",
        "offer_text": "Selected home appliances",
        "smartphones": "Smartphones",
        "computers": "Washing machines",
        "home_appliances": "Kitchen appliances",
        "tv": "TVs",
        "conditioners": "Air conditioners",
        "cleaning_appliances": "Cleaning appliances",
        "market_deals": "Below market price",
        "kitchen_deals": "For the kitchen",
        "seasonal_appliances": "Seasonal appliances",
        "home_comfort": "Home comfort",
        "curated_picks": "Curated picks",
        "featured_products": "Featured products",
        "view_all": "View all",
        "why": "Why TechShop",
        "confidence_title": "Designed for confident online shopping.",
        "problem_solution_title": "Problems TechShop solves",
        "problem_solution_text": "Clear catalog, predictable checkout, mobile-first layout, and admin order control.",
        "problem_1": "Hard product search",
        "solution_1": "Search, category, price filter, and sorting.",
        "problem_2": "Unclear purchase flow",
        "solution_2": "Cart, delivery, payment choice, and confirmation.",
        "problem_3": "Weak mobile experience",
        "solution_3": "Catalog, cart, and checkout adapt to phone screens.",
        "problem_4": "No order control",
        "solution_4": "Orders are saved and managed from Django admin.",
        "smart_filters": "Smart filters",
        "smart_filters_text": "Find products by category, price, and rating.",
        "session_cart": "Session cart",
        "session_cart_text": "Products stay in the cart while customers browse.",
        "validated_checkout": "Validated checkout",
        "validated_checkout_text": "Clean forms reduce ordering mistakes.",
        "catalog_title": "Shop home appliances.",
        "search": "Search",
        "category": "Category",
        "maximum_price": "Maximum price ($)",
        "sort_by": "Sort by",
        "featured": "Featured",
        "price_low_high": "Price: low to high",
        "price_high_low": "Price: high to low",
        "top_rated": "Top rated",
        "apply_filters": "Apply filters",
        "reset": "Reset",
        "products_found": "products found",
        "ready_to_order": "Home appliances, ready to order",
        "no_products": "No products match your filters.",
        "out_of_stars": "out of 5 stars",
        "add_to_cart": "Add to cart",
        "reviews": "reviews",
        "reviews_title": "Reviews",
        "no_reviews": "No reviews yet. Write the first review.",
        "send_review": "Send review",
        "quantity": "Quantity",
        "related_products": "Related products",
        "shopping_cart": "Shopping cart",
        "review_order": "Review your order.",
        "each": "each",
        "update": "Update",
        "remove": "Remove",
        "empty_cart": "Your cart is empty. Explore the catalog to add products.",
        "no_favorites": "No favorites yet. Tap the heart on products you like.",
        "order_summary": "Order summary",
        "subtotal": "Subtotal",
        "delivery": "Delivery",
        "free": "Free",
        "total": "Total",
        "continue_shopping": "Continue shopping",
        "complete_order": "Complete your order.",
        "place_order": "Place order",
        "your_items": "Your items",
        "checkout_title": "Order checkout",
        "customer_info": "Your information",
        "full_name_hint": "We will use this name for the order.",
        "delivery_method": "Receiving method",
        "delivery_to_door": "Delivery",
        "delivery_to_door_hint": "Courier delivers to your address",
        "pickup_point": "Pickup point",
        "pickup_point_hint": "Pick up from the nearest store",
        "address_not_selected": "Address not selected",
        "address_hint": "Enter city and address below.",
        "payment_method_title": "Choose payment method",
        "payment_card": "Card",
        "payment_card_hint": "UZCARD, HUMO, Visa, Mastercard",
        "payment_installment": "Installment",
        "payment_installment_hint": "Through partner services",
        "payment_cash": "Pay on delivery",
        "payment_cash_hint": "Pay by cash or card when receiving",
        "card_services": "Click, Payme, Octobank",
        "installment_services": "IMAN, TBC Nasiya, Alif, Uzum Nasiya",
        "promo_placeholder": "Do you have a promo code?",
        "apply": "Apply",
        "products_count": "items",
        "terms_note": "By placing the order, you agree to the public offer terms.",
        "discount": "Discount",
        "total_discount": "Total discount",
        "products_price": "Products price",
        "order_accepted": "Order accepted",
        "order_accepted_text": "Your order has been created. Our manager will contact you shortly to confirm the details.",
        "order_number": "Order number",
        "order_date": "Order date",
        "recipient": "Recipient",
        "payment": "Payment",
        "delivery_address": "Delivery address",
        "order_status": "Status",
        "status_new": "New",
        "manager_call": "Manager call",
        "manager_call_text": "We will call you soon and confirm delivery.",
        "go_home": "Go home",
        "track_order": "Track order",
        "about_project": "About project",
        "about_title": "Online shop for household appliances.",
        "about_text": "This diploma project demonstrates a production-style ecommerce platform with catalog browsing, filtering, cart management, and checkout validation.",
        "project_goals": "Project goals",
        "project_goals_text": "Build a clean, responsive, SEO-friendly online store that helps general customers quickly compare and buy electronics.",
        "architecture": "Architecture",
        "architecture_text": "Django views, reusable templates, session cart, static assets.",
        "ux": "UX",
        "ux_text": "Responsive catalog, modern product cards, clear checkout flow.",
        "scalability": "Scalability",
        "scalability_text": "Ready to replace dummy data with database models and payment APIs.",
        "contact_title": "Contact TechShop.",
        "customer_service": "Customer service",
        "phone": "Phone",
        "email": "Email",
        "address": "Address",
        "name": "Name",
        "your_name": "Your name",
        "message": "Message",
        "help_placeholder": "How can we help?",
        "send_message": "Send message",
    },
    "uz": {
        "home": "Bosh sahifa",
        "products": "Mahsulotlar",
        "price": "Narx",
        "rating": "Reyting",
        "about": "Biz haqimizda",
        "contact": "Aloqa",
        "cart": "Savatcha",
        "catalog": "Katalog",
        "checkout": "Buyurtma",
        "support": "Yordam",
        "footer_text": "Maishiy texnika, yetkazib berish va qulay buyurtma uchun zamonaviy onlayn do'kon.",
        "ad": "Reklama",
        "catalog_sections": "Katalog bo'limlari",
        "all_smartphones": "Barcha smartfonlar",
        "large_appliances": "Yirik texnika",
        "refrigerators": "Muzlatkichlar",
        "washing_machines": "Kir yuvish mashinalari",
        "dishwashers": "Idish yuvish mashinalari",
        "ovens": "Duxovkalar",
        "kitchen_for": "Oshxona uchun",
        "microwaves": "Mikroto'lqinli pechlar",
        "air_fryers": "Air fryerlar",
        "coffee_machines": "Qahva mashinalari",
        "blenders": "Blenderlar",
        "meat_grinders": "Qiymalagichlar",
        "climate_care": "Iqlim va parvarish",
        "air_purifiers": "Havo tozalagichlar",
        "water_heaters": "Suv isitgichlar",
        "irons": "Dazmollar",
        "hair_dryers": "Fenlar",
        "brands": "Brendlar",
        "sales_discounts": "Aksiyalar va chegirmalar",
        "air_conditioners": "Havo sovutgichlar",
        "vacuum_cleaners": "Changyutgichlar",
        "laptops": "Noutbuklar",
        "login": "Kirish",
        "login_with_phone": "Telefon orqali kirish",
        "login_with_google": "Google orqali kirish",
        "login_or": "yoki",
        "favorites": "Saralangan",
        "compare": "Taqqoslash",
        "compare_products": "Mahsulotlarni taqqoslash",
        "add_to_compare": "Taqqoslash",
        "remove_from_compare": "Tanlangan",
        "comparison_empty": "Taqqoslash uchun hali mahsulot tanlanmagan.",
        "recently_viewed": "Oxirgi ko'rilganlar",
        "stock": "Ombor",
        "availability": "Mavjudlik",
        "search_placeholder": "Smartfon, texnika va brendlarni izlash",
        "login_title": "TechShop'ga kirish",
        "phone_placeholder": "+998 00 000-00-00",
        "get_code": "Faollashtirish kodini oling",
        "code_title": "Tasdiqlash kodini kiriting",
        "code_placeholder": "4 xonali kod",
        "confirm_code": "Tasdiqlash",
        "demo_code": "Demo kod",
        "change_phone": "Raqamni o'zgartirish",
        "logout": "Chiqish",
        "signed_in_as": "Profil",
        "profile_title": "Mening ma'lumotlarim",
        "full_name": "FIO",
        "profile_type": "Profil turi",
        "google_account": "Google akkaunt",
        "phone_account": "Telefon orqali",
        "back_to_catalog": "Katalogga qaytish",
        "my_information": "Mening ma'lumotlarim",
        "orders": "Buyurtmalar",
        "sign_in_or_create": "Kirish yoki shaxsiy kabinet yaratish",
        "sign_in": "Kirish",
        "agreement": "Davom etish orqali shaxsiy ma'lumotlarni qayta ishlash va ommaviy oferta shartlariga rozilik bildirasiz.",
        "new_season": "Yangi mavsum texnologiyalari",
        "hero_title": "Har bir xona uchun maishiy texnika.",
        "hero_text": "Muzlatkich, kir yuvish mashinasi, televizor, oshxona texnikasi va konditsionerlarni bitta ixcham katalogdan toping.",
        "shop_catalog": "Katalogni ko'rish",
        "featured_deals": "Tanlangan takliflar",
        "warranty": "2 yillik kafolat",
        "secure_checkout": "Xavfsiz to'lov",
        "fast_delivery": "Tez yetkazib berish",
        "offer_title": "18% gacha chegirma",
        "offer_text": "Tanlangan maishiy texnika",
        "smartphones": "Smartfonlar",
        "computers": "Kir yuvish mashinalari",
        "home_appliances": "Oshxona texnikasi",
        "tv": "Televizorlar",
        "conditioners": "Konditsionerlar",
        "cleaning_appliances": "Tozalash texnikasi",
        "market_deals": "Bozordan arzon",
        "kitchen_deals": "Oshxona uchun",
        "seasonal_appliances": "Mavsumiy texnika",
        "home_comfort": "Uy uchun qulaylik",
        "curated_picks": "Tavsiya etilganlar",
        "featured_products": "Tanlangan mahsulotlar",
        "view_all": "Barchasini ko'rish",
        "why": "Nega TechShop",
        "confidence_title": "Ishonchli onlayn xarid uchun yaratilgan.",
        "problem_solution_title": "TechShop qanday muammoni yechadi",
        "problem_solution_text": "Aniq katalog, tushunarli checkout, mobilga mos dizayn va admin orqali buyurtma nazorati.",
        "problem_1": "Mahsulotni topish qiyin",
        "solution_1": "Qidiruv, kategoriya, narx filtri va saralash.",
        "problem_2": "Buyurtma jarayoni tushunarsiz",
        "solution_2": "Savatcha, yetkazish, to'lov tanlovi va tasdiqlash.",
        "problem_3": "Telefon ekranida noqulaylik",
        "solution_3": "Katalog, savatcha va checkout telefon ekraniga moslashadi.",
        "problem_4": "Buyurtmalar nazorati yo'q",
        "solution_4": "Buyurtmalar saqlanadi va admin paneldan boshqariladi.",
        "smart_filters": "Aqlli filtrlar",
        "smart_filters_text": "Mahsulotlarni kategoriya, narx va reyting bo'yicha toping.",
        "session_cart": "Sessiya savatchasi",
        "session_cart_text": "Mahsulotlar ko'rish davomida savatchada saqlanadi.",
        "validated_checkout": "Tekshirilgan buyurtma",
        "validated_checkout_text": "Qulay formalar xatolarni kamaytiradi.",
        "catalog_title": "Maishiy texnikani xarid qiling.",
        "search": "Qidirish",
        "category": "Kategoriya",
        "maximum_price": "Maksimal narx (so'm)",
        "sort_by": "Saralash",
        "featured": "Tavsiya etilgan",
        "price_low_high": "Narx: arzonidan qimmatiga",
        "price_high_low": "Narx: qimmatidan arzoniga",
        "top_rated": "Yuqori reyting",
        "apply_filters": "Filtrlarni qo'llash",
        "reset": "Tozalash",
        "products_found": "ta mahsulot topildi",
        "ready_to_order": "Maishiy texnika, buyurtmaga tayyor",
        "no_products": "Filtrlarga mos mahsulot topilmadi.",
        "out_of_stars": "5 yulduzdan",
        "add_to_cart": "Savatchaga qo'shish",
        "reviews": "sharh",
        "reviews_title": "Sharhlar",
        "no_reviews": "Hali yozilgan sharh yo'q. Birinchi sharhni yozing.",
        "send_review": "Sharh yuborish",
        "quantity": "Miqdor",
        "related_products": "O'xshash mahsulotlar",
        "shopping_cart": "Savatcha",
        "review_order": "Buyurtmani tekshiring.",
        "each": "dona",
        "update": "Yangilash",
        "remove": "O'chirish",
        "empty_cart": "Savatcha bo'sh. Mahsulot qo'shish uchun katalogni ko'ring.",
        "no_favorites": "Hali saralangan mahsulot yo'q. Yoqgan mahsulotingizdagi yurakchani bosing.",
        "order_summary": "Buyurtma xulosasi",
        "subtotal": "Oraliq summa",
        "delivery": "Yetkazib berish",
        "free": "Bepul",
        "total": "Jami",
        "continue_shopping": "Xaridni davom ettirish",
        "complete_order": "Buyurtmani yakunlang.",
        "place_order": "Buyurtma berish",
        "your_items": "Mahsulotlaringiz",
        "checkout_title": "Buyurtmani rasmiylashtirish",
        "customer_info": "Sizning ma'lumotlaringiz",
        "full_name_hint": "Buyurtma shu ism orqali rasmiylashtiriladi.",
        "delivery_method": "Qabul qilish usuli",
        "delivery_to_door": "Yetkazib berish",
        "delivery_to_door_hint": "Kuryer manzilingizga olib boradi",
        "pickup_point": "Olib ketish",
        "pickup_point_hint": "Yaqin do'kondan olib ketasiz",
        "address_not_selected": "Manzil tanlanmagan",
        "address_hint": "Shahar va manzilni pastda kiriting.",
        "payment_method_title": "To'lov usulini tanlang",
        "payment_card": "Karta",
        "payment_card_hint": "UZCARD, HUMO, Visa, Mastercard",
        "payment_installment": "Muddatli to'lov",
        "payment_installment_hint": "Hamkor servislar orqali",
        "payment_cash": "Olinganda to'lov",
        "payment_cash_hint": "Naqd yoki karta orqali to'lash",
        "card_services": "Click, Payme, Octobank",
        "installment_services": "IMAN, TBC Nasiya, Alif, Uzum Nasiya",
        "promo_placeholder": "Promo-kod bormi?",
        "apply": "Qo'llash",
        "products_count": "ta mahsulot",
        "terms_note": "Buyurtmani tasdiqlash orqali ommaviy oferta shartlariga rozilik bildirasiz.",
        "discount": "Chegirma",
        "total_discount": "Umumiy chegirma",
        "products_price": "Mahsulotlar narxi",
        "order_accepted": "Buyurtma qabul qilindi",
        "order_accepted_text": "Buyurtmangiz yaratildi. Menejerimiz tez orada siz bilan bog'lanib, ma'lumotlarni tasdiqlaydi.",
        "order_number": "Buyurtma raqami",
        "order_date": "Buyurtma sanasi",
        "recipient": "Qabul qiluvchi",
        "payment": "To'lov",
        "delivery_address": "Yetkazib berish manzili",
        "order_status": "Holat",
        "status_new": "Yangi",
        "manager_call": "Menejer qo'ng'irog'i",
        "manager_call_text": "Tez orada qo'ng'iroq qilib, yetkazib berishni tasdiqlaymiz.",
        "go_home": "Bosh sahifa",
        "track_order": "Buyurtmani kuzatish",
        "about_project": "Loyiha haqida",
        "about_title": "Maishiy texnika uchun zamonaviy onlayn do'kon.",
        "about_text": "Bu diplom loyihasi katalog, filtr, savatcha va buyurtma tekshiruvi bilan ishlab chiqarish uslubidagi ecommerce platformani ko'rsatadi.",
        "project_goals": "Loyiha maqsadlari",
        "project_goals_text": "Mijozlarga elektronikani tez solishtirish va xarid qilishga yordam beradigan qulay, moslashuvchan va SEO-friendly do'kon yaratish.",
        "architecture": "Arxitektura",
        "architecture_text": "Django view'lari, qayta ishlatiladigan template'lar, sessiya savatchasi va static fayllar.",
        "ux": "UX",
        "ux_text": "Moslashuvchan katalog, zamonaviy product kartalar va tushunarli checkout jarayoni.",
        "scalability": "Kengaytirish",
        "scalability_text": "Demo ma'lumotlarni database modellari va payment API'lari bilan almashtirishga tayyor.",
        "contact_title": "TechShop bilan bog'laning.",
        "customer_service": "Mijozlar xizmati",
        "phone": "Telefon",
        "email": "Email",
        "address": "Manzil",
        "name": "Ism",
        "your_name": "Ismingiz",
        "message": "Xabar",
        "help_placeholder": "Qanday yordam bera olamiz?",
        "send_message": "Xabar yuborish",
    },
}


def current_language(request):
    explicit_language = request.session.get("django_language") or request.COOKIES.get(settings.LANGUAGE_COOKIE_NAME)
    return (explicit_language or settings.LANGUAGE_CODE or "uz").split("-")[0]


def ui_text(request):
    lang = current_language(request)
    return {
        "ui": UI_TEXT.get(lang, UI_TEXT["en"]),
        "current_language": lang,
        "auth_phone": request.session.get("auth_phone", ""),
        "auth_email": request.session.get("auth_email", ""),
        "auth_name": request.session.get("auth_name", ""),
        "auth_display": request.session.get("auth_name") or request.session.get("auth_email") or request.session.get("auth_phone", ""),
        "auth_pending_phone": request.session.get("auth_pending_phone", ""),
        "auth_demo_code": request.session.get("auth_code", ""),
    }


def cart_summary(request):
    cart = request.session.get("cart", {})
    count = sum(cart.values())
    total = 0
    for slug, quantity in cart.items():
        product = get_product(slug)
        if product:
            total += product["price"] * quantity
    lang = current_language(request)
    return {"cart_count": count, "cart_total": total, "cart_total_display": format_price(total, lang)}


def favorites_summary(request):
    favorites = request.session.get("favorites", [])
    return {"favorites_count": len(favorites), "favorite_slugs": set(favorites)}
