from pathlib import Path


PRODUCTS = [
    {
        "id": 1,
        "slug": "lg-instaview-refrigerator",
        "name": "LG InstaView Refrigerator",
        "category": "refrigerators",
        "brand": "LG",
        "price": 1799,
        "old_price": 1999,
        "rating": 4.8,
        "reviews": 231,
        "badge": "Super narx",
        "image": "https://loremflickr.com/900/900/refrigerator,appliance?lock=101",
        "short": "Keng hajmli, inverter motorli va oynali eshikli smart muzlatkich.",
        "description": "Oziq-ovqatni uzoqroq yangi saqlash, energiyani tejash va oshxonaga zamonaviy ko'rinish berish uchun yaratilgan muzlatkich.",
        "specs": ["635L sig'im", "Inverter kompressor", "Door-in-door panel", "Smart cooling"],
        "featured": True,
    },
    {
        "id": 2,
        "slug": "bosch-series-6-washer",
        "name": "Bosch Series 6 Washer",
        "category": "washers",
        "brand": "Bosch",
        "price": 799,
        "old_price": 899,
        "rating": 4.7,
        "reviews": 319,
        "badge": "Ko'p sotilgan",
        "image": "https://loremflickr.com/900/900/washing-machine,appliance?lock=102",
        "short": "Jim ishlaydigan, suv va elektrni tejaydigan frontal kir yuvish mashinasi.",
        "description": "Oilaviy foydalanish uchun qulay, shovqini past va tez yuvish rejimlari bilan jihozlangan ishonchli kir yuvish mashinasi.",
        "specs": ["9kg sig'im", "EcoSilence Drive", "SpeedPerfect rejimi", "A+++ samaradorlik"],
        "featured": True,
    },
    {
        "id": 3,
        "slug": "samsung-55-crystal-uhd",
        "name": "Samsung 55 Crystal UHD TV",
        "category": "tv",
        "brand": "Samsung",
        "price": 699,
        "old_price": 849,
        "rating": 4.8,
        "reviews": 456,
        "badge": "Chegirma",
        "image": "https://loremflickr.com/900/900/television,electronics?lock=103",
        "short": "4K tasvir, smart ilovalar va katta ekranli zamonaviy televizor.",
        "description": "Kinolar, sport va seriallarni katta ekranda tiniq tasvir bilan ko'rish uchun yaxshi tanlov.",
        "specs": ["55 dyuym", "4K UHD", "Smart TV", "HDR qo'llovi"],
        "featured": True,
    },
    {
        "id": 4,
        "slug": "artel-split-conditioner",
        "name": "Artel Split Conditioner",
        "category": "climate",
        "brand": "Artel",
        "price": 429,
        "old_price": 499,
        "rating": 4.6,
        "reviews": 188,
        "badge": "Yoz mavsumi",
        "image": "https://loremflickr.com/900/900/air-conditioner,appliance?lock=104",
        "short": "Uy va ofis uchun sovutish-isitish rejimli split konditsioner.",
        "description": "Issiq kunlarda xonani tez sovutadi, qishda esa qo'shimcha isitish rejimi bilan qulaylik beradi.",
        "specs": ["12 BTU", "Sovutish va isitish", "Turbo rejim", "Past shovqin"],
        "featured": True,
    },
    {
        "id": 5,
        "slug": "philips-air-fryer-xl",
        "name": "Philips Air Fryer XL",
        "category": "kitchen",
        "brand": "Philips",
        "price": 189,
        "old_price": 229,
        "rating": 4.9,
        "reviews": 512,
        "badge": "Oshxona hiti",
        "image": "https://loremflickr.com/900/900/air-fryer,kitchen-appliance?lock=105",
        "short": "Kam yog' bilan tez va mazali taom tayyorlaydigan air fryer.",
        "description": "Kartoshka, tovuq, sabzavot va desertlarni kam yog' bilan tez tayyorlash uchun ixcham oshxona texnikasi.",
        "specs": ["6.2L hajm", "Rapid Air texnologiyasi", "Sensor boshqaruv", "Idish yuvgichga mos"],
        "featured": False,
    },
    {
        "id": 6,
        "slug": "dyson-vacuum-cleaner",
        "name": "Dyson Cordless Vacuum",
        "category": "cleaning",
        "brand": "Dyson",
        "price": 549,
        "old_price": 649,
        "rating": 4.7,
        "reviews": 274,
        "badge": "Premium",
        "image": "https://loremflickr.com/900/900/vacuum-cleaner,appliance?lock=106",
        "short": "Simsiz, kuchli tortish quvvatiga ega yengil changyutgich.",
        "description": "Uy tozaligini tezroq va qulayroq qilish uchun simsiz ishlaydigan, yengil va kuchli changyutgich.",
        "specs": ["60 daqiqa ishlash", "HEPA filtr", "Simsiz dizayn", "Ko'p nasadkali to'plam"],
        "featured": False,
    },
    {
        "id": 7,
        "slug": "haier-dishwasher",
        "name": "Haier Dishwasher",
        "category": "kitchen",
        "brand": "Haier",
        "price": 499,
        "old_price": 579,
        "rating": 4.6,
        "reviews": 143,
        "badge": "Tejamkor",
        "image": "https://loremflickr.com/900/900/dishwasher,kitchen-appliance?lock=107",
        "short": "Suvni tejaydigan, oilaviy foydalanishga mos idish yuvish mashinasi.",
        "description": "Kundalik idishlarni toza va tejamkor yuvish uchun bir nechta dasturga ega zamonaviy mashina.",
        "specs": ["14 komplekt", "6 dastur", "Tez yuvish", "Past suv sarfi"],
        "featured": True,
    },
    {
        "id": 8,
        "slug": "shivaki-microwave",
        "name": "Shivaki Microwave Oven",
        "category": "kitchen",
        "brand": "Shivaki",
        "price": 119,
        "old_price": 149,
        "rating": 4.5,
        "reviews": 209,
        "badge": "Arzon narx",
        "image": "https://loremflickr.com/900/900/microwave-oven,kitchen-appliance?lock=108",
        "short": "Tez isitish va muzdan tushirish uchun ixcham mikroto'lqinli pech.",
        "description": "Kichik oshxona uchun ham mos, oddiy boshqaruvli va kundalik foydalanishga qulay mikroto'lqinli pech.",
        "specs": ["23L hajm", "800W quvvat", "Defrost rejimi", "Mexanik boshqaruv"],
        "featured": False,
    },
    {
        "id": 9,
        "slug": "beko-two-door-refrigerator",
        "name": "Beko Two Door Refrigerator",
        "category": "refrigerators",
        "brand": "Beko",
        "price": 649,
        "old_price": 749,
        "rating": 4.6,
        "reviews": 167,
        "badge": "Yangi",
        "image": "https://loremflickr.com/900/900/fridge,appliance?lock=109",
        "short": "Ikki eshikli, ixcham oshxonalar uchun qulay muzlatkich.",
        "description": "Kundalik mahsulotlarni tartibli saqlash uchun keng javonlar va tejamkor sovutish tizimiga ega muzlatkich.",
        "specs": ["340L sig'im", "No Frost", "LED yoritish", "A+ energiya sinfi"],
        "featured": True,
    },
    {
        "id": 10,
        "slug": "samsung-ww90-washer",
        "name": "Samsung WW90 Washer",
        "category": "washers",
        "brand": "Samsung",
        "price": 729,
        "old_price": 829,
        "rating": 4.8,
        "reviews": 298,
        "badge": "Eco Bubble",
        "image": "https://loremflickr.com/900/900/laundry,washing-machine?lock=110",
        "short": "Eco Bubble texnologiyali, katta hajmli kir yuvish mashinasi.",
        "description": "Kiyimlarni yumshoq, samarali va energiyani tejagan holda yuvish uchun zamonaviy frontal kir yuvish mashinasi.",
        "specs": ["9kg sig'im", "Eco Bubble", "Digital inverter", "Bug' bilan yuvish"],
        "featured": True,
    },
    {
        "id": 11,
        "slug": "lg-43-smart-tv",
        "name": "LG 43 Smart TV",
        "category": "tv",
        "brand": "LG",
        "price": 419,
        "old_price": 499,
        "rating": 4.7,
        "reviews": 341,
        "badge": "Smart TV",
        "image": "https://loremflickr.com/900/900/smart-tv,television?lock=111",
        "short": "Ixcham xona uchun 43 dyuymli smart televizor.",
        "description": "YouTube, streaming ilovalari va Full HD tasvir bilan kundalik tomosha uchun qulay televizor.",
        "specs": ["43 dyuym", "Full HD", "webOS", "Wi-Fi"],
        "featured": False,
    },
    {
        "id": 12,
        "slug": "gree-inverter-conditioner",
        "name": "Gree Inverter Conditioner",
        "category": "climate",
        "brand": "Gree",
        "price": 579,
        "old_price": 679,
        "rating": 4.8,
        "reviews": 222,
        "badge": "Inverter",
        "image": "https://loremflickr.com/900/900/air-conditioner,home?lock=112",
        "short": "Tejamkor inverter motorli sovutish va isitish konditsioneri.",
        "description": "Xonani tez sovutadi, elektr sarfini kamaytiradi va yil davomida barqaror iqlim yaratadi.",
        "specs": ["12 BTU", "Inverter motor", "A++ energiya", "Wi-Fi ready"],
        "featured": True,
    },
    {
        "id": 13,
        "slug": "tefal-steam-iron",
        "name": "Tefal Steam Iron",
        "category": "cleaning",
        "brand": "Tefal",
        "price": 79,
        "old_price": 99,
        "rating": 4.5,
        "reviews": 187,
        "badge": "Uy parvarishi",
        "image": "https://loremflickr.com/900/900/steam-iron,appliance?lock=113",
        "short": "Kuchli bug' bilan kiyimlarni tez tekislaydigan dazmol.",
        "description": "Kundalik kiyim parvarishi uchun yengil, tez qiziydigan va kuchli bug' beradigan dazmol.",
        "specs": ["2600W quvvat", "Bug' zarbasi", "Keramik taglik", "Tomchilatmaslik"],
        "featured": False,
    },
    {
        "id": 14,
        "slug": "delonghi-coffee-machine",
        "name": "DeLonghi Coffee Machine",
        "category": "kitchen",
        "brand": "DeLonghi",
        "price": 349,
        "old_price": 429,
        "rating": 4.9,
        "reviews": 376,
        "badge": "Barista",
        "image": "https://loremflickr.com/900/900/coffee-machine,kitchen?lock=114",
        "short": "Espresso va cappuccino uchun ixcham qahva mashinasi.",
        "description": "Uyda barista uslubida espresso, latte va cappuccino tayyorlash uchun qulay qahva mashinasi.",
        "specs": ["15 bar bosim", "Sut ko'pirtirgich", "1.8L bak", "Avto tozalash"],
        "featured": True,
    },
    {
        "id": 15,
        "slug": "panasonic-blender",
        "name": "Panasonic Blender",
        "category": "kitchen",
        "brand": "Panasonic",
        "price": 69,
        "old_price": 89,
        "rating": 4.4,
        "reviews": 119,
        "badge": "Arzon",
        "image": "https://loremflickr.com/900/900/blender,kitchen-appliance?lock=115",
        "short": "Smoothie, sous va pyure tayyorlash uchun kuchli blender.",
        "description": "Oshxonada tezkor aralashtirish, maydalash va ichimliklar tayyorlash uchun oddiy va ishonchli blender.",
        "specs": ["700W quvvat", "1.5L idish", "2 tezlik", "Muz maydalash"],
        "featured": False,
    },
    {
        "id": 16,
        "slug": "xiaomi-air-purifier",
        "name": "Xiaomi Air Purifier",
        "category": "climate",
        "brand": "Xiaomi",
        "price": 199,
        "old_price": 249,
        "rating": 4.7,
        "reviews": 264,
        "badge": "Toza havo",
        "image": "https://loremflickr.com/900/900/air-purifier,appliance?lock=116",
        "short": "Chang, allergen va hidlarni kamaytiradigan havo tozalagich.",
        "description": "Uy havosini tozalash, allergenlarni kamaytirish va xonada qulay muhit yaratish uchun smart havo tozalagich.",
        "specs": ["HEPA filtr", "Smart app", "31-48 m2", "Tungi rejim"],
        "featured": False,
    },
    {
        "id": 17,
        "slug": "midea-water-heater",
        "name": "Midea Water Heater",
        "category": "climate",
        "brand": "Midea",
        "price": 159,
        "old_price": 199,
        "rating": 4.5,
        "reviews": 101,
        "badge": "Qish uchun",
        "image": "https://loremflickr.com/900/900/water-heater,appliance?lock=117",
        "short": "Uy uchun ixcham va xavfsiz elektr suv isitgich.",
        "description": "Dush va oshxona uchun barqaror issiq suv ta'minlaydigan, xavfsizlik himoyali suv isitgich.",
        "specs": ["50L hajm", "1500W quvvat", "Himoya klapani", "ECO rejim"],
        "featured": False,
    },
    {
        "id": 18,
        "slug": "braun-meat-grinder",
        "name": "Braun Meat Grinder",
        "category": "kitchen",
        "brand": "Braun",
        "price": 139,
        "old_price": 169,
        "rating": 4.6,
        "reviews": 156,
        "badge": "Oshxona",
        "image": "https://loremflickr.com/900/900/meat-grinder,kitchen-appliance?lock=118",
        "short": "Go'sht va sabzavotlarni tez maydalaydigan elektr qiymalagich.",
        "description": "Uy sharoitida kotlet, qiyma va turli taomlar tayyorlash uchun kuchli motorli qiymalagich.",
        "specs": ["1800W quvvat", "3 panjara", "Reverse rejim", "Kolbasa nasadkasi"],
        "featured": False,
    },
    {
        "id": 19,
        "slug": "rowenta-hair-dryer",
        "name": "Rowenta Hair Dryer",
        "category": "cleaning",
        "brand": "Rowenta",
        "price": 59,
        "old_price": 79,
        "rating": 4.4,
        "reviews": 137,
        "badge": "Parvarish",
        "image": "https://loremflickr.com/900/900/hair-dryer,appliance?lock=119",
        "short": "Kuchli havo oqimi va sovuq havo rejimli fen.",
        "description": "Sochni tez quritish va kundalik parvarish uchun ergonomik, yengil va kuchli fen.",
        "specs": ["2200W quvvat", "3 harorat", "Sovuq havo", "Ionizatsiya"],
        "featured": False,
    },
    {
        "id": 20,
        "slug": "ariston-built-in-oven",
        "name": "Ariston Built-in Oven",
        "category": "kitchen",
        "brand": "Ariston",
        "price": 389,
        "old_price": 459,
        "rating": 4.7,
        "reviews": 205,
        "badge": "Built-in",
        "image": "https://loremflickr.com/900/900/built-in-oven,kitchen-appliance?lock=120",
        "short": "Pishiriq va taomlar uchun o'rnatiladigan elektr duxovka.",
        "description": "Oshxona mebeliga chiroyli joylashadigan, bir nechta pishirish rejimiga ega elektr duxovka.",
        "specs": ["71L hajm", "8 rejim", "Grill", "A energiya sinfi"],
        "featured": True,
    },
    {
        "id": 21,
        "slug": "iphone-15-pro-256gb",
        "name": "iPhone 15 Pro 256GB",
        "category": "smartphones",
        "brand": "Apple",
        "price": 1199,
        "old_price": 1299,
        "rating": 4.9,
        "reviews": 148,
        "badge": "Premium",
        "image": "https://loremflickr.com/900/900/iphone,smartphone?lock=221",
        "short": "Titan korpusli, kuchli kamera va A17 Pro chipli Apple smartfoni.",
        "description": "Kundalik ish, kontent yaratish va premium mobil tajriba uchun kuchli iPhone modeli.",
        "specs": ["256GB xotira", "6.1 dyuym OLED", "A17 Pro", "48MP kamera"],
        "featured": True,
    },
    {
        "id": 22,
        "slug": "samsung-galaxy-s24-256gb",
        "name": "Samsung Galaxy S24 256GB",
        "category": "smartphones",
        "brand": "Samsung",
        "price": 899,
        "old_price": 999,
        "rating": 4.8,
        "reviews": 203,
        "badge": "Galaxy AI",
        "image": "https://loremflickr.com/900/900/samsung,smartphone?lock=222",
        "short": "Yorqin AMOLED ekran, kuchli kamera va zamonaviy Galaxy AI funksiyalari.",
        "description": "Foto, video, o'yin va ish uchun balanslangan flagman Samsung smartfoni.",
        "specs": ["256GB xotira", "Dynamic AMOLED", "50MP kamera", "5G"],
        "featured": True,
    },
    {
        "id": 23,
        "slug": "redmi-note-13-pro-256gb",
        "name": "Redmi Note 13 Pro 256GB",
        "category": "smartphones",
        "brand": "Redmi",
        "price": 329,
        "old_price": 399,
        "rating": 4.7,
        "reviews": 276,
        "badge": "Xiaomi",
        "image": "https://loremflickr.com/900/900/redmi,smartphone?lock=223",
        "short": "Katta AMOLED ekran, tez zaryad va yaxshi kamera bilan arzon smartfon.",
        "description": "Narx va imkoniyat balansi kerak bo'lgan foydalanuvchilar uchun Redmi smartfoni.",
        "specs": ["256GB xotira", "AMOLED 120Hz", "200MP kamera", "Fast charge"],
        "featured": True,
    },
    {
        "id": 24,
        "slug": "redmi-12-128gb",
        "name": "Redmi 12 128GB",
        "category": "smartphones",
        "brand": "Redmi",
        "price": 179,
        "old_price": 219,
        "rating": 4.5,
        "reviews": 132,
        "badge": "Arzon",
        "image": "https://loremflickr.com/900/900/xiaomi,phone?lock=224",
        "short": "Kundalik foydalanish uchun katta ekranli va qulay narxli Redmi telefoni.",
        "description": "Qo'ng'iroq, messenjer, video va oddiy o'yinlar uchun yaxshi byudjet smartfon.",
        "specs": ["128GB xotira", "6.79 dyuym ekran", "50MP kamera", "5000mAh"],
        "featured": False,
    },
    {
        "id": 25,
        "slug": "iphone-16-pro-max-256gb",
        "name": "iPhone 16 Pro Max 256GB",
        "category": "smartphones",
        "brand": "Apple",
        "price": 1399,
        "old_price": 1499,
        "rating": 4.9,
        "reviews": 96,
        "badge": "Yangi",
        "image": "",
        "short": "Katta ProMotion ekran, kuchli kamera va Apple Intelligence uchun premium iPhone.",
        "description": "Kontent yaratish, ish va mobil fotografiya uchun eng kuchli Apple flagmani.",
        "specs": ["256GB xotira", "6.9 dyuym OLED", "A18 Pro", "48MP kamera"],
        "featured": True,
    },
    {
        "id": 26,
        "slug": "iphone-14-128gb",
        "name": "iPhone 14 128GB",
        "category": "smartphones",
        "brand": "Apple",
        "price": 699,
        "old_price": 799,
        "rating": 4.7,
        "reviews": 214,
        "badge": "Apple",
        "image": "",
        "short": "Kundalik foydalanish uchun barqaror kamera va iOS ekotizimli iPhone.",
        "description": "Ishonchli iOS tajribasi, yaxshi kamera va uzoq muddatli yangilanish kerak bo'lganlar uchun iPhone.",
        "specs": ["128GB xotira", "6.1 dyuym OLED", "A15 Bionic", "12MP kamera"],
        "featured": False,
    },
    {
        "id": 27,
        "slug": "samsung-galaxy-a55-256gb",
        "name": "Samsung Galaxy A55 256GB",
        "category": "smartphones",
        "brand": "Samsung",
        "price": 429,
        "old_price": 499,
        "rating": 4.7,
        "reviews": 187,
        "badge": "Galaxy",
        "image": "",
        "short": "AMOLED ekran, mustahkam korpus va yaxshi kamera bilan o'rta segment smartfoni.",
        "description": "Narx va imkoniyat balansi yaxshi bo'lgan Samsung Galaxy modeli.",
        "specs": ["256GB xotira", "Super AMOLED", "50MP kamera", "5000mAh"],
        "featured": True,
    },
    {
        "id": 28,
        "slug": "samsung-galaxy-a35-128gb",
        "name": "Samsung Galaxy A35 128GB",
        "category": "smartphones",
        "brand": "Samsung",
        "price": 329,
        "old_price": 389,
        "rating": 4.6,
        "reviews": 154,
        "badge": "Ommabop",
        "image": "",
        "short": "Katta AMOLED ekran va 5G bilan kundalik ishlarga mos Samsung.",
        "description": "Messenjer, video, o'yin va ish uchun qulay Galaxy A seriyasi.",
        "specs": ["128GB xotira", "AMOLED 120Hz", "50MP kamera", "5G"],
        "featured": False,
    },
    {
        "id": 29,
        "slug": "redmi-note-14-pro-256gb",
        "name": "Redmi Note 14 Pro 256GB",
        "category": "smartphones",
        "brand": "Redmi",
        "price": 379,
        "old_price": 449,
        "rating": 4.7,
        "reviews": 168,
        "badge": "Redmi",
        "image": "",
        "short": "Yorqin ekran, katta batareya va tez zaryadli Redmi Note modeli.",
        "description": "Kamera, ekran va batareya bo'yicha kuchli balans kerak bo'lganlar uchun Redmi.",
        "specs": ["256GB xotira", "AMOLED 120Hz", "200MP kamera", "Fast charge"],
        "featured": True,
    },
    {
        "id": 30,
        "slug": "xiaomi-14t-256gb",
        "name": "Xiaomi 14T 256GB",
        "category": "smartphones",
        "brand": "Xiaomi",
        "price": 549,
        "old_price": 629,
        "rating": 4.8,
        "reviews": 119,
        "badge": "Xiaomi",
        "image": "",
        "short": "Kuchli chipset, sifatli kamera va premium ekranli Xiaomi smartfoni.",
        "description": "Foto, video va o'yinlarda kuchli ishlaydigan Xiaomi T seriyasi.",
        "specs": ["256GB xotira", "AMOLED 144Hz", "Leica kamera", "5G"],
        "featured": True,
    },
    {
        "id": 31,
        "slug": "oppo-reno-12-256gb",
        "name": "Oppo Reno 12 256GB",
        "category": "smartphones",
        "brand": "Oppo",
        "price": 439,
        "old_price": 499,
        "rating": 4.6,
        "reviews": 142,
        "badge": "Oppo",
        "image": "",
        "short": "Nozik dizayn, portret kamera va tez zaryad bilan Reno seriyasi.",
        "description": "Chiroyli dizayn va kamera imkoniyati muhim bo'lgan foydalanuvchilar uchun Oppo.",
        "specs": ["256GB xotira", "AMOLED", "50MP portret", "80W charge"],
        "featured": False,
    },
    {
        "id": 32,
        "slug": "oppo-a78-128gb",
        "name": "Oppo A78 128GB",
        "category": "smartphones",
        "brand": "Oppo",
        "price": 229,
        "old_price": 279,
        "rating": 4.5,
        "reviews": 131,
        "badge": "Arzon",
        "image": "",
        "short": "Kundalik ishlar uchun qulay, tez zaryadli Oppo A seriyasi.",
        "description": "Byudjet segmentida chiroyli ekran va barqaror ishlash kerak bo'lganlar uchun.",
        "specs": ["128GB xotira", "AMOLED", "67W charge", "5000mAh"],
        "featured": False,
    },
    {
        "id": 33,
        "slug": "honor-90-256gb",
        "name": "Honor 90 256GB",
        "category": "smartphones",
        "brand": "Honor",
        "price": 399,
        "old_price": 459,
        "rating": 4.7,
        "reviews": 177,
        "badge": "Honor",
        "image": "",
        "short": "Yupqa korpus, katta OLED ekran va yuqori aniqlikdagi kamera.",
        "description": "Ijtimoiy tarmoqlar, video va kundalik ishlar uchun chiroyli Honor smartfoni.",
        "specs": ["256GB xotira", "OLED 120Hz", "200MP kamera", "66W charge"],
        "featured": True,
    },
    {
        "id": 34,
        "slug": "honor-x9b-256gb",
        "name": "Honor X9b 256GB",
        "category": "smartphones",
        "brand": "Honor",
        "price": 319,
        "old_price": 379,
        "rating": 4.6,
        "reviews": 122,
        "badge": "Mustahkam",
        "image": "",
        "short": "Mustahkam ekran, katta batareya va zamonaviy dizaynli Honor.",
        "description": "Katta batareya va chidamli korpus kerak bo'lganlar uchun Honor X seriyasi.",
        "specs": ["256GB xotira", "AMOLED", "108MP kamera", "5800mAh"],
        "featured": False,
    },
    {
        "id": 35,
        "slug": "vivo-v30-256gb",
        "name": "Vivo V30 256GB",
        "category": "smartphones",
        "brand": "Vivo",
        "price": 449,
        "old_price": 519,
        "rating": 4.7,
        "reviews": 116,
        "badge": "Vivo",
        "image": "",
        "short": "Selfie va portret uchun kuchli kamera, nozik dizayn va AMOLED ekran.",
        "description": "Foto va video kontent yaratishga qulay Vivo V seriyasi.",
        "specs": ["256GB xotira", "AMOLED 120Hz", "50MP selfie", "80W charge"],
        "featured": False,
    },
    {
        "id": 36,
        "slug": "realme-12-pro-plus-256gb",
        "name": "Realme 12 Pro+ 256GB",
        "category": "smartphones",
        "brand": "Realme",
        "price": 389,
        "old_price": 459,
        "rating": 4.6,
        "reviews": 104,
        "badge": "Realme",
        "image": "",
        "short": "Periskop kamera, katta ekran va tez zaryadli Realme smartfoni.",
        "description": "Zoom kamera va zamonaviy dizayn kerak bo'lgan foydalanuvchilar uchun Realme.",
        "specs": ["256GB xotira", "OLED", "64MP periskop", "67W charge"],
        "featured": False,
    },
    {
        "id": 37,
        "slug": "nothing-phone-2a-256gb",
        "name": "Nothing Phone 2a 256GB",
        "category": "smartphones",
        "brand": "Nothing",
        "price": 349,
        "old_price": 399,
        "rating": 4.6,
        "reviews": 89,
        "badge": "Design",
        "image": "",
        "short": "Shaffof dizayn, toza interfeys va yorqin AMOLED ekranli Nothing.",
        "description": "Minimal dizayn va silliq Android tajribasi xohlaydiganlar uchun Nothing Phone.",
        "specs": ["256GB xotira", "AMOLED 120Hz", "50MP dual", "Glyph lights"],
        "featured": False,
    },
    {
        "id": 38,
        "slug": "infinix-note-40-pro-256gb",
        "name": "Infinix Note 40 Pro 256GB",
        "category": "smartphones",
        "brand": "Infinix",
        "price": 269,
        "old_price": 329,
        "rating": 4.5,
        "reviews": 97,
        "badge": "Infinix",
        "image": "",
        "short": "Katta AMOLED ekran, tez zaryad va yaxshi narxli Infinix.",
        "description": "Katta xotira va zamonaviy ekran kerak, lekin byudjet cheklangan foydalanuvchilar uchun.",
        "specs": ["256GB xotira", "AMOLED", "108MP kamera", "70W charge"],
        "featured": False,
    },
    {
        "id": 39,
        "slug": "tecno-camon-30-256gb",
        "name": "Tecno Camon 30 256GB",
        "category": "smartphones",
        "brand": "Tecno",
        "price": 249,
        "old_price": 299,
        "rating": 4.5,
        "reviews": 83,
        "badge": "Tecno",
        "image": "",
        "short": "Katta xotira, yorqin ekran va kamera imkoniyati yaxshi Tecno modeli.",
        "description": "Narxi qulay, xotirasi katta va dizayni zamonaviy smartfon kerak bo'lganlar uchun.",
        "specs": ["256GB xotira", "AMOLED", "50MP kamera", "5000mAh"],
        "featured": False,
    },
    {
        "id": 40,
        "slug": "macbook-air-m2-256gb",
        "name": "MacBook Air M2 256GB",
        "category": "laptops",
        "brand": "Apple",
        "price": 1099,
        "old_price": 1199,
        "rating": 4.9,
        "reviews": 184,
        "badge": "Yengil",
        "image": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=max&w=1100&q=85",
        "short": "Yengil, jim va uzoq quvvat ushlaydigan MacBook Air noutbuki.",
        "description": "O'qish, ish, dasturlash va kundalik vazifalar uchun qulay Apple noutbuki.",
        "specs": ["Apple M2", "8GB RAM", "256GB SSD", "13.6 dyuym Liquid Retina"],
        "featured": True,
    },
    {
        "id": 41,
        "slug": "lenovo-ideapad-15-512gb",
        "name": "Lenovo IdeaPad 15 512GB",
        "category": "laptops",
        "brand": "Lenovo",
        "price": 629,
        "old_price": 729,
        "rating": 4.6,
        "reviews": 121,
        "badge": "Ish uchun",
        "image": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=max&w=1100&q=85",
        "short": "Ofis, o'qish va masofaviy ish uchun universal Lenovo noutbuki.",
        "description": "Katta ekran, tez SSD va qulay klaviatura bilan kundalik ishlarga mos noutbuk.",
        "specs": ["Intel Core i5", "8GB RAM", "512GB SSD", "15.6 dyuym Full HD"],
        "featured": False,
    },
    {
        "id": 42,
        "slug": "samsung-bespoke-fridge",
        "name": "Samsung Bespoke Refrigerator",
        "category": "refrigerators",
        "brand": "Samsung",
        "price": 1299,
        "old_price": 1499,
        "rating": 4.8,
        "reviews": 174,
        "badge": "Bespoke",
        "image": "",
        "short": "No Frost, zamonaviy dizayn va katta hajmli Samsung muzlatkichi.",
        "description": "Oilaviy foydalanish uchun katta sig'im, energiya tejamkorlik va premium dizayn.",
        "specs": ["520L sig'im", "No Frost", "Digital inverter", "Multi airflow"],
        "featured": True,
    },
    {
        "id": 43,
        "slug": "artel-hd-455-fridge",
        "name": "Artel HD 455 Refrigerator",
        "category": "refrigerators",
        "brand": "Artel",
        "price": 549,
        "old_price": 629,
        "rating": 4.5,
        "reviews": 98,
        "badge": "Mahalliy",
        "image": "",
        "short": "Uy uchun qulay hajmli, tejamkor Artel muzlatkichi.",
        "description": "Kundalik mahsulotlarni tartibli saqlash uchun ishonchli va arzon muzlatkich.",
        "specs": ["330L sig'im", "A+ energiya", "LED chiroq", "Past shovqin"],
        "featured": False,
    },
    {
        "id": 44,
        "slug": "haier-side-by-side-fridge",
        "name": "Haier Side-by-Side Refrigerator",
        "category": "refrigerators",
        "brand": "Haier",
        "price": 999,
        "old_price": 1149,
        "rating": 4.7,
        "reviews": 141,
        "badge": "Katta hajm",
        "image": "",
        "short": "Katta oila uchun side-by-side formatdagi Haier muzlatkichi.",
        "description": "Keng kamera, barqaror sovutish va zamonaviy oshxona uchun mos dizayn.",
        "specs": ["560L sig'im", "No Frost", "Inverter", "Elektron panel"],
        "featured": False,
    },
    {
        "id": 45,
        "slug": "shivaki-compact-fridge",
        "name": "Shivaki Compact Refrigerator",
        "category": "refrigerators",
        "brand": "Shivaki",
        "price": 299,
        "old_price": 349,
        "rating": 4.4,
        "reviews": 76,
        "badge": "Ixcham",
        "image": "",
        "short": "Ofis, yotoqxona yoki kichik oshxona uchun ixcham muzlatkich.",
        "description": "Joy kam bo'lgan xonalar uchun arzon va ishonchli sovutish yechimi.",
        "specs": ["150L sig'im", "A energiya", "Mini freezer", "Ixcham dizayn"],
        "featured": False,
    },
    {
        "id": 46,
        "slug": "lg-f2v5-washer",
        "name": "LG F2V5 Washer",
        "category": "washers",
        "brand": "LG",
        "price": 689,
        "old_price": 779,
        "rating": 4.8,
        "reviews": 203,
        "badge": "AI DD",
        "image": "",
        "short": "AI DD motorli, kiyim turini tanib yuvadigan LG kir yuvish mashinasi.",
        "description": "Kiyimlarni ehtiyotkor yuvish, bug' rejimi va tejamkor motor bilan jihozlangan.",
        "specs": ["8.5kg sig'im", "AI DD", "Steam", "Inverter motor"],
        "featured": True,
    },
    {
        "id": 47,
        "slug": "artel-automatic-washer",
        "name": "Artel Automatic Washer",
        "category": "washers",
        "brand": "Artel",
        "price": 379,
        "old_price": 449,
        "rating": 4.5,
        "reviews": 87,
        "badge": "Arzon",
        "image": "",
        "short": "Kundalik yuvish uchun avtomatik Artel kir yuvish mashinasi.",
        "description": "Byudjet narxda oddiy boshqaruv va kerakli yuvish dasturlari.",
        "specs": ["7kg sig'im", "15 dastur", "Tez yuvish", "LED display"],
        "featured": False,
    },
    {
        "id": 48,
        "slug": "beko-front-load-washer",
        "name": "Beko Front Load Washer",
        "category": "washers",
        "brand": "Beko",
        "price": 529,
        "old_price": 599,
        "rating": 4.6,
        "reviews": 113,
        "badge": "Tejamkor",
        "image": "",
        "short": "Suv va elektrni tejaydigan frontal Beko kir yuvish mashinasi.",
        "description": "Oilaviy foydalanishga mos, jim ishlaydigan va ishonchli frontal model.",
        "specs": ["8kg sig'im", "A+++ energiya", "Quick wash", "Inverter"],
        "featured": False,
    },
    {
        "id": 49,
        "slug": "haier-8kg-washer",
        "name": "Haier 8kg Washer",
        "category": "washers",
        "brand": "Haier",
        "price": 489,
        "old_price": 559,
        "rating": 4.5,
        "reviews": 92,
        "badge": "8kg",
        "image": "",
        "short": "8kg sig'imli, oilaviy foydalanish uchun Haier kir yuvish mashinasi.",
        "description": "Katta baraban, bir nechta dastur va tez yuvish rejimi bilan qulay model.",
        "specs": ["8kg sig'im", "1200 rpm", "15 dastur", "Child lock"],
        "featured": False,
    },
    {
        "id": 50,
        "slug": "artel-50-android-tv",
        "name": "Artel 50 Android TV",
        "category": "tv",
        "brand": "Artel",
        "price": 399,
        "old_price": 469,
        "rating": 4.5,
        "reviews": 118,
        "badge": "Android",
        "image": "",
        "short": "50 dyuymli Android TV, YouTube va ilovalar bilan.",
        "description": "Uy kinoteatri uchun katta ekran, smart ilovalar va qulay interfeys.",
        "specs": ["50 dyuym", "4K UHD", "Android TV", "Wi-Fi"],
        "featured": False,
    },
    {
        "id": 51,
        "slug": "sony-bravia-55-tv",
        "name": "Sony Bravia 55 TV",
        "category": "tv",
        "brand": "Sony",
        "price": 899,
        "old_price": 999,
        "rating": 4.9,
        "reviews": 221,
        "badge": "Bravia",
        "image": "",
        "short": "Ranglari aniq, kino va sport uchun premium Sony televizori.",
        "description": "Yuqori sifatli tasvir, HDR va smart platforma bilan premium tajriba.",
        "specs": ["55 dyuym", "4K HDR", "Google TV", "Dolby Audio"],
        "featured": True,
    },
    {
        "id": 52,
        "slug": "xiaomi-tv-a2-43",
        "name": "Xiaomi TV A2 43",
        "category": "tv",
        "brand": "Xiaomi",
        "price": 329,
        "old_price": 389,
        "rating": 4.6,
        "reviews": 156,
        "badge": "Xiaomi",
        "image": "",
        "short": "Google TV va 4K tasvirli qulay narxdagi Xiaomi televizori.",
        "description": "Streaming, YouTube va kundalik tomosha uchun ixcham smart TV.",
        "specs": ["43 dyuym", "4K", "Google TV", "Bluetooth"],
        "featured": False,
    },
    {
        "id": 53,
        "slug": "lg-dual-inverter-ac",
        "name": "LG Dual Inverter AC",
        "category": "climate",
        "brand": "LG",
        "price": 629,
        "old_price": 729,
        "rating": 4.8,
        "reviews": 184,
        "badge": "Dual Inverter",
        "image": "",
        "short": "Tez sovutish va past elektr sarfi bilan LG konditsioneri.",
        "description": "Yozda tez sovutadi, inverter motor elektr sarfini kamaytiradi.",
        "specs": ["12 BTU", "Dual inverter", "Wi-Fi", "Past shovqin"],
        "featured": True,
    },
    {
        "id": 54,
        "slug": "samsung-windfree-ac",
        "name": "Samsung WindFree AC",
        "category": "climate",
        "brand": "Samsung",
        "price": 699,
        "old_price": 799,
        "rating": 4.8,
        "reviews": 147,
        "badge": "WindFree",
        "image": "",
        "short": "Yumshoq havo tarqatish texnologiyali Samsung konditsioneri.",
        "description": "Xonani sovutadi, lekin to'g'ridan-to'g'ri sovuq shamol bermaydi.",
        "specs": ["12 BTU", "WindFree", "Inverter", "SmartThings"],
        "featured": False,
    },
    {
        "id": 55,
        "slug": "ballu-air-purifier",
        "name": "Ballu Air Purifier",
        "category": "climate",
        "brand": "Ballu",
        "price": 149,
        "old_price": 189,
        "rating": 4.5,
        "reviews": 88,
        "badge": "HEPA",
        "image": "",
        "short": "Chang va allergenlarni kamaytiradigan HEPA havo tozalagich.",
        "description": "Yotoqxona va bolalar xonasi uchun ixcham havo tozalash qurilmasi.",
        "specs": ["HEPA filtr", "Tungi rejim", "30 m2", "Past shovqin"],
        "featured": False,
    },
    {
        "id": 56,
        "slug": "philips-garment-steamer",
        "name": "Philips Garment Steamer",
        "category": "cleaning",
        "brand": "Philips",
        "price": 89,
        "old_price": 119,
        "rating": 4.5,
        "reviews": 101,
        "badge": "Bug'",
        "image": "",
        "short": "Kiyimlarni osilgan holatda tez tekislaydigan steamer.",
        "description": "Ko'ylak, kostyum va nozik matolar uchun qulay bug'li parvarish qurilmasi.",
        "specs": ["1600W", "Tez qizish", "Bug' oqimi", "Ixcham"],
        "featured": False,
    },
    {
        "id": 57,
        "slug": "karcher-vacuum-cleaner",
        "name": "Karcher Vacuum Cleaner",
        "category": "cleaning",
        "brand": "Karcher",
        "price": 199,
        "old_price": 249,
        "rating": 4.6,
        "reviews": 124,
        "badge": "Kuchli",
        "image": "",
        "short": "Uy va ofis tozaligi uchun kuchli Karcher changyutgich.",
        "description": "Qattiq pol, gilam va kundalik tozalash uchun kuchli tortish quvvatiga ega.",
        "specs": ["1800W", "HEPA filtr", "4L bak", "Ko'p nasadka"],
        "featured": False,
    },
    {
        "id": 58,
        "slug": "samsung-jet-vacuum",
        "name": "Samsung Jet Vacuum",
        "category": "cleaning",
        "brand": "Samsung",
        "price": 399,
        "old_price": 479,
        "rating": 4.7,
        "reviews": 117,
        "badge": "Simsiz",
        "image": "",
        "short": "Simsiz, yengil va kuchli Samsung Jet changyutgichi.",
        "description": "Tez tozalash, yuqori tortish quvvati va qulay zaryad bazasi bilan.",
        "specs": ["Simsiz", "60 daqiqa", "Jet Cyclone", "HEPA"],
        "featured": True,
    },
    {
        "id": 59,
        "slug": "asus-vivobook-15",
        "name": "Asus VivoBook 15",
        "category": "laptops",
        "brand": "Asus",
        "price": 579,
        "old_price": 679,
        "rating": 4.6,
        "reviews": 136,
        "badge": "O'qish",
        "image": "",
        "short": "O'qish, ofis va kundalik ishlar uchun yengil Asus noutbuki.",
        "description": "Tez SSD, Full HD ekran va qulay klaviatura bilan universal noutbuk.",
        "specs": ["Intel Core i5", "8GB RAM", "512GB SSD", "15.6 dyuym"],
        "featured": False,
    },
    {
        "id": 60,
        "slug": "hp-pavilion-15",
        "name": "HP Pavilion 15",
        "category": "laptops",
        "brand": "HP",
        "price": 699,
        "old_price": 799,
        "rating": 4.7,
        "reviews": 149,
        "badge": "Universal",
        "image": "",
        "short": "Ish, o'qish va multimedia uchun balanslangan HP Pavilion.",
        "description": "Kundalik produktivlik, video ko'rish va masofaviy ish uchun yaxshi tanlov.",
        "specs": ["Ryzen 5", "16GB RAM", "512GB SSD", "Full HD"],
        "featured": False,
    },
    {
        "id": 61,
        "slug": "acer-aspire-7",
        "name": "Acer Aspire 7",
        "category": "laptops",
        "brand": "Acer",
        "price": 849,
        "old_price": 949,
        "rating": 4.7,
        "reviews": 111,
        "badge": "Performance",
        "image": "",
        "short": "Dasturlash, dizayn va yengil o'yinlar uchun kuchli Acer noutbuki.",
        "description": "Kuchli protsessor va diskret grafika bilan ish va o'qishga mos model.",
        "specs": ["Intel Core i5", "16GB RAM", "RTX grafika", "512GB SSD"],
        "featured": True,
    },
    {
        "id": 62,
        "slug": "dell-inspiron-15",
        "name": "Dell Inspiron 15",
        "category": "laptops",
        "brand": "Dell",
        "price": 649,
        "old_price": 749,
        "rating": 4.6,
        "reviews": 128,
        "badge": "Ish uchun",
        "image": "",
        "short": "Barqaror ishlash va mustahkam korpusli Dell noutbuki.",
        "description": "Ofis, o'qish va masofaviy ish uchun ishonchli Dell Inspiron modeli.",
        "specs": ["Intel Core i5", "8GB RAM", "512GB SSD", "15.6 dyuym"],
        "featured": False,
    },
]

CATEGORIES = {
    "all": "All products",
    "smartphones": "Smartphones",
    "laptops": "Laptops",
    "refrigerators": "Refrigerators",
    "washers": "Washing machines",
    "tv": "TV",
    "climate": "Climate",
    "kitchen": "Kitchen appliances",
    "cleaning": "Cleaning",
}

UZ_CATEGORIES = {
    "all": "Barcha mahsulotlar",
    "smartphones": "Smartfonlar",
    "laptops": "Noutbuklar",
    "refrigerators": "Muzlatkichlar",
    "washers": "Kir yuvish mashinalari",
    "tv": "Televizorlar",
    "climate": "Konditsionerlar",
    "kitchen": "Oshxona texnikasi",
    "cleaning": "Tozalash texnikasi",
}

UZ_PRODUCT_TEXT = {}

EN_BADGES = {
    "Super narx": "Super price",
    "Ko'p sotilgan": "Top seller",
    "Chegirma": "Discount",
    "Yoz mavsumi": "Summer deal",
    "Oshxona hiti": "Kitchen hit",
    "Tejamkor": "Efficient",
    "Arzon narx": "Low price",
    "Yangi": "New",
    "Uy parvarishi": "Home care",
    "Toza havo": "Clean air",
    "Qish uchun": "Winter ready",
    "Oshxona": "Kitchen",
    "Parvarish": "Care",
    "Arzon": "Budget",
    "Ommabop": "Popular",
    "Mustahkam": "Durable",
    "Yengil": "Lightweight",
    "Ish uchun": "For work",
    "Mahalliy": "Local",
    "Katta hajm": "Large capacity",
    "Ixcham": "Compact",
    "Bug'": "Steam",
    "Kuchli": "Powerful",
    "Simsiz": "Cordless",
    "O'qish": "Study",
}

EN_CATEGORY_COPY = {
    "smartphones": (
        "{name} is a balanced smartphone for everyday apps, photos, video, and smooth mobile use.",
        "{brand} smartphone with a modern display, reliable performance, and practical camera features.",
    ),
    "laptops": (
        "{name} is a practical laptop for study, office work, browsing, and daily productivity.",
        "{brand} laptop with fast storage, a comfortable keyboard, and reliable everyday performance.",
    ),
    "refrigerators": (
        "{name} keeps food fresh longer and fits neatly into a modern home kitchen.",
        "{brand} refrigerator with spacious storage, efficient cooling, and a clean modern design.",
    ),
    "washers": (
        "{name} is built for reliable family laundry with useful programs and efficient washing.",
        "{brand} washing machine with practical wash modes, solid capacity, and everyday reliability.",
    ),
    "tv": (
        "{name} is a smart TV for movies, sport, streaming apps, and clear everyday viewing.",
        "{brand} TV with a sharp screen, smart features, and a comfortable viewing experience.",
    ),
    "climate": (
        "{name} helps keep the room comfortable with efficient cooling and practical climate control.",
        "{brand} climate appliance for cleaner air, comfortable temperature, and everyday home comfort.",
    ),
    "kitchen": (
        "{name} makes everyday cooking easier with practical controls and a compact kitchen-friendly design.",
        "{brand} kitchen appliance for quick preparation, simple use, and reliable daily cooking.",
    ),
    "cleaning": (
        "{name} helps with quick home care, cleaning, and daily maintenance tasks.",
        "{brand} cleaning appliance with practical power, convenient handling, and everyday reliability.",
    ),
}

EN_SPEC_REPLACEMENTS = {
    "xotira": "storage",
    "dyuym": "inch",
    "kamera": "camera",
    "sig'im": "capacity",
    "hajm": "capacity",
    "quvvat": "power",
    "rejimi": "mode",
    "rejim": "mode",
    "dastur": "programs",
    "komplekt": "place settings",
    "daqiqa ishlash": "minutes runtime",
    "daqiqa": "minutes",
    "filtr": "filter",
    "Simsiz dizayn": "Cordless design",
    "Simsiz": "Cordless",
    "Ko'p nasadkali to'plam": "Multi-attachment set",
    "Ko'p nasadka": "Multiple nozzles",
    "Sovutish va isitish": "Cooling and heating",
    "Past shovqin": "Low noise",
    "A+++ samaradorlik": "A+++ efficiency",
    "A+++ energiya": "A+++ energy rating",
    "A++ energiya": "A++ energy rating",
    "A+ energiya": "A+ energy rating",
    "A energiya sinfi": "A energy class",
    "A energiya": "A energy rating",
    "HDR qo'llovi": "HDR support",
    "Rapid Air texnologiyasi": "Rapid Air technology",
    "Sensor boshqaruv": "Touch control",
    "Idish yuvgichga mos": "Dishwasher safe",
    "Tez yuvish": "Quick wash",
    "Past suv sarfi": "Low water use",
    "Mexanik boshqaruv": "Mechanical control",
    "LED yoritish": "LED lighting",
    "Bug' bilan yuvish": "Steam wash",
    "Bug' zarbasi": "Steam boost",
    "Bug' oqimi": "Steam flow",
    "Keramik taglik": "Ceramic soleplate",
    "Tomchilatmaslik": "Anti-drip",
    "Sut ko'pirtirgich": "Milk frother",
    "Avto tozalash": "Auto cleaning",
    "Muz maydalash": "Ice crushing",
    "Tungi rejim": "Night mode",
    "Himoya klapani": "Safety valve",
    "panjara": "grinding plates",
    "Kolbasa nasadkasi": "Sausage attachment",
    "Sovuq havo": "Cool air",
    "Tez qizish": "Fast heat-up",
    "Ixcham": "Compact",
    "Elektron panel": "Electronic panel",
    "dyuym ekran": "inch display",
    "grafika": "graphics",
}

EN_PRODUCT_TEXT = {
    "redmi-note-13-pro-256gb": {
        "short": "Affordable smartphone with a large AMOLED display, fast charging, and a strong camera.",
        "description": "A Redmi smartphone for users who want a strong balance of price, display quality, camera, and performance.",
    },
}

USD_TO_UZS = 12500
BASE_DIR = Path(__file__).resolve().parent.parent

MARKET_IMAGES = {
    "refrigerators": "https://mini-io-api.texnomart.uz/catalog/special-category/7/74a09808-7198-496a-b704-158399923abd.png",
    "washers": "/static/img/categories/washing-machine.svg",
    "tv": "https://mini-io-api.texnomart.uz/catalog/special-category/9/e84d9227-6eef-4f6c-94f4-a26258c5d5a1.png",
    "climate": "https://mini-io-api.texnomart.uz/catalog/special-category/8/61521f46-27bb-4ba1-8fa7-34f3bc6e9530.png",
    "cleaning": "https://mini-io-api.texnomart.uz/catalog/special-category/5/ade607e8-e08e-40a1-85c1-b291327fe412.png",
    "kitchen": "https://mini-io-api.texnomart.uz/catalog/special-category/23/a206c805-83f1-4965-9da7-876b8124fcee.png",
    "smartphones": "https://mini-io-api.texnomart.uz/catalog/special-category/4/aa4237cb-9bc4-4941-8535-277ca7831f48.png",
    "laptops": "https://mini-io-api.texnomart.uz/catalog/special-category/22/1f3896fc-fbb9-4d2f-ac2e-17df4bf4959b.png",
}

LOCAL_IMAGE_CATEGORIES = {"refrigerators", "washers", "tv", "climate", "kitchen", "cleaning", "laptops"}

PRODUCT_IMAGES = {
    "macbook-air-m2-256gb": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=max&w=1100&q=85",
    "lenovo-ideapad-15-512gb": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=max&w=1100&q=85",
}


def format_price(amount, language):
    if language == "uz":
        uzs_amount = int(round(amount * USD_TO_UZS))
        return f"{uzs_amount:,}".replace(",", " ") + " so'm"
    return f"${amount:,.0f}"


def price_to_usd(amount, language):
    if language == "uz":
        return amount / USD_TO_UZS
    return amount


def get_product(slug):
    return next((product for product in PRODUCTS if product["slug"] == slug), None)


def category_labels(language):
    return UZ_CATEGORIES if language == "uz" else CATEGORIES


def _english_product_copy(product):
    override = EN_PRODUCT_TEXT.get(product["slug"], {})
    description_template, short_template = EN_CATEGORY_COPY.get(
        product["category"],
        ("{name} is a practical product for everyday use.", "{brand} product for everyday use."),
    )
    return {
        "short": override.get("short", short_template.format(name=product["name"], brand=product["brand"])),
        "description": override.get("description", description_template.format(name=product["name"], brand=product["brand"])),
    }


def _translate_spec_to_en(spec):
    translated = spec
    for source, target in sorted(EN_SPEC_REPLACEMENTS.items(), key=lambda item: len(item[0]), reverse=True):
        translated = translated.replace(source, target)
    return translated


def localize_product(product, language):
    if not product:
        return product
    localized = product.copy()
    if language != "uz":
        copy = _english_product_copy(product)
        localized["short"] = copy["short"]
        localized["description"] = copy["description"]
        localized["specs"] = [_translate_spec_to_en(spec) for spec in product["specs"]]
        localized["badge"] = EN_BADGES.get(product["badge"], product["badge"])
    if product["category"] == "smartphones":
        image_dir = "phones"
        localized["image"] = f"/static/img/products/{image_dir}/{product['slug']}.jpg"
    elif product["category"] in LOCAL_IMAGE_CATEGORIES:
        image_dir = product["category"]
        localized["image"] = f"/static/img/products/{image_dir}/{product['slug']}.jpg"
    else:
        image_dir = ""
        localized["image"] = PRODUCT_IMAGES.get(product["slug"]) or MARKET_IMAGES.get(product["category"], product["image"])
    gallery = [localized["image"]]
    if image_dir:
        product_dir = BASE_DIR / "static" / "img" / "products" / image_dir
        for index in (2, 3, 4):
            gallery_path = product_dir / f"{product['slug']}-{index}.jpg"
            if gallery_path.exists():
                gallery.append(f"/static/img/products/{image_dir}/{product['slug']}-{index}.jpg")
    localized["gallery"] = gallery
    localized["category_label"] = category_labels(language).get(product["category"], product["category"].title())
    localized["monthly_price"] = max(1, round(product["price"] / 12))
    localized["price_display"] = format_price(product["price"], language)
    localized["old_price_display"] = format_price(product["old_price"], language)
    localized["monthly_price_display"] = format_price(localized["monthly_price"], language)
    return localized


def localize_products(products, language):
    return [localize_product(product, language) for product in products]
