# Generated by Django 5.2.1 on 2026-05-13 15:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24, unique=True, verbose_name='Buyurtma raqami')),
                ('full_name', models.CharField(max_length=80, verbose_name='Mijoz F.I.Sh.')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=24, verbose_name='Telefon')),
                ('city', models.CharField(max_length=60, verbose_name='Shahar')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('payment_method', models.CharField(choices=[('card', 'Karta orqali'), ('cash', 'Yetkazilganda naqd'), ('transfer', "Bank o'tkazmasi")], max_length=20, verbose_name="To'lov usuli")),
                ('delivery_method', models.CharField(choices=[('delivery', 'Yetkazib berish'), ('pickup', 'Olib ketish')], default='delivery', max_length=20, verbose_name='Yetkazish usuli')),
                ('total', models.PositiveIntegerField(verbose_name='Jami summa')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('processing', 'Jarayonda'), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_slug', models.SlugField(max_length=120, verbose_name='Mahsulot slug')),
                ('product_name', models.CharField(max_length=160, verbose_name='Mahsulot nomi')),
                ('product_image', models.URLField(blank=True, max_length=500, verbose_name='Mahsulot rasmi')),
                ('unit_price', models.PositiveIntegerField(verbose_name='Dona narxi')),
                ('quantity', models.PositiveIntegerField(verbose_name='Soni')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Jami')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Buyurtma mahsuloti',
                'verbose_name_plural': 'Buyurtma mahsulotlari',
            },
        ),
    ]
